
# Model configuration - will be auto-filled with embedding dimensions
model:
  # These could be auto-detected from embeddings:
  embedding_dim: 1024
  patch_size: 16
  target_size: [256, 256]  # Size of original images/labels
  hidden_dim: 512
  lr: 1e-3
  wd: 1e-4
  b1: 0.9
  b2: 0.95
  focal_alpha: 0.75
  use_aspp: False
  use_residual: True

data:
  train_embedd_dir: data/AI4B/FR_train_200/images/embeddings_checkpoints_Prithvi_EO_V2_300M/
  train_label_dir: data/AI4B/FR_train_200/masks/
  val_embedd_dir: data/AI4B/FR_val_40/images/embeddings_checkpoints_Prithvi_EO_V2_300M/
  val_label_dir: data/AI4B/FR_val_40/masks/
  test_embedd_dir: data/AI4B/ES_100/images/embeddings_checkpoints_Prithvi_EO_V2_300M/
  test_label_dir: data/AI4B/ES_100/masks/
  target_size: [256, 256]
  batch_size: 16  
  num_workers: 4

trainer:
  accelerator: auto
  # strategy: ddp
  devices: auto
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 1
  accumulate_grad_batches: 1
  default_root_dir: checkpoints/boundary_embeddings
  fast_dev_run: False
  num_sanity_val_steps: 0

  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: ignaciomasari-eodc
        project: clay-embedding-boundary-detection
        log_model: false
    # - class_path: lightning.pytorch.loggers.CSVLogger
    #   init_args:
    #     save_dir: "lightning_logs"
    #     name: "clay-embedding-boundary-detection"

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/boundary_embeddings
        auto_insert_metric_name: False
        filename: 'embedding-boundary_epoch-{epoch:02d}_val-f1-{val/f1:.4f}'
        monitor: val/f1
        mode: max
        save_last: True
        save_top_k: 1
        save_weights_only: True
        verbose: True
    
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 10
        mode: min
    
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO